"""Incremental indexer of Claude Code transcripts (~/.claude/projects/**/*.jsonl and ~/<uuid>*.jsonl from Orca),
Codex sessions (~/.codex/sessions) and OpenCode conversations (the SQLite ~/.local/share/opencode/opencode.db).

Run: uv --directory C:\\dev\\claude-worker\\lore run python -m lore.index [--text-only] [--remask]

--text-only: full text only - chunks are stored WITHOUT vectors and the embedding model is never
loaded or downloaded. That is the indexer of a machine with the knowledge module but without the
lore module (the daily harvest reads chunks, never a vector); the installer puts the flag into the
LoreIndex task. The mode of the last pass is recorded (db.META_INDEX_MODE), so missing vectors read
as a chosen state, not a fault; the first normal pass switches it back, and `python -m lore.migrate`
gives the text-only chunks their vectors.
"""

from __future__ import annotations

import json
import os
import re
import sqlite3
import sys
import time
from collections.abc import Iterator
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from .db import (DB_PATH, MODELS, NEXT_TABLE, PROJECTS_DIR, active_model, connect, embed_passages, has_table,
                 log, now_iso, record_index_mode)
from .masking import mask

CHUNK_SIZE = 1500
OVERLAP = 200
STEP = CHUNK_SIZE - OVERLAP
MAX_TOOL_INPUT = 200
MAX_TOOL_RESULT = 400
MIN_LENGTH = 3

TURN_SEPARATOR = "\n\n"
MIXED_ROLE = "conversation"
# the last group is not written — the session may still extend it; but we do not wait forever
TAIL_CLOSING_AGE_S = 24 * 60 * 60

LOCK_PATH = DB_PATH.with_suffix(".lock")
LOCK_STALE_S = 15 * 60

# sessions started by Orca drop their transcripts loose in the home directory
HOME_DIR = Path.home()
CODEX_SESSIONS_DIR = HOME_DIR / ".codex" / "sessions"
# OpenCode keeps its conversations in one SQLite database, not in transcript files; None = under
# HOME_DIR, looked up at call time (a test that moves HOME_DIR moves the database with it)
OPENCODE_DB: Path | None = None
OPENCODE_PROJECT = "opencode"
META_OPENCODE = "opencode_status"  # the outcome of the last OpenCode read: "ok ..." / "BLAD ..." / "absent"
HOME_PROJECT = "orca"
_UUID = re.compile(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", re.I)

# user rows generated by Claude Code itself, worthless as memory
_NOISE_PREFIXES = (
    "<task-notification>",
    "<local-command",
    "<ide_opened_file>",
    "<ide_selection>",
    "<command-name>",
    "<command-message>",
    "<bash-input>",
    "<bash-stdout>",
    "<bash-stderr>",
    "[Request interrupted",
    "Base directory for this skill",
    "Caveat: The messages below",
)
_SYSTEM_REMINDER = re.compile(r"<system-reminder>.*?</system-reminder>", re.DOTALL)


@dataclass
class Turn:
    """A single turn from a transcript — the input material for grouping."""

    line: int
    ts: str
    role: str
    text: str


@dataclass
class Chunk:
    line: int
    part: int
    ts: str
    role: str
    text: str


@dataclass
class ParsedRecord:
    """One transcript record normalized at the format seam."""

    turns: list[tuple[str, str]]
    project: str | None = None
    session: str | None = None


# ---------------------------------------------------------------- record parsing

def _text_from_content(content) -> str:
    """Joins `text` blocks (or returns the string) — for tool results."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "\n".join(b.get("text", "") for b in content if isinstance(b, dict) and b.get("type") == "text")
    return ""


def _input_digest(inp) -> str:
    if isinstance(inp, dict):
        # the most telling fields first
        for k in ("command", "description", "pattern", "file_path", "query", "prompt", "zapytanie"):
            if k in inp and isinstance(inp[k], str):
                return " ".join(inp[k].split())[:MAX_TOOL_INPUT]
        s = json.dumps(inp, ensure_ascii=False)
    else:
        s = str(inp)
    return " ".join(s.split())[:MAX_TOOL_INPUT]


def _clean_user_text(t: str) -> str:
    t = _SYSTEM_REMINDER.sub("", t).strip()
    if not t or t.startswith(_NOISE_PREFIXES):
        return ""
    return t


def _claude_turns(rec: dict, role_prefix: str = "") -> list[tuple[str, str]]:
    """Returns normalized turns from one Claude Code JSONL row."""
    typ = rec.get("type")
    if typ not in ("user", "assistant"):
        return []
    if rec.get("isMeta") or rec.get("isApiErrorMessage"):
        return []
    msg = rec.get("message") or {}
    content = msg.get("content")
    out: list[tuple[str, str]] = []

    if typ == "user":
        if rec.get("isCompactSummary"):
            t = _text_from_content(content).strip()
            if t:
                out.append((role_prefix + "summary", t))
            return out
        if isinstance(content, str):
            t = _clean_user_text(content)
            if t:
                out.append((role_prefix + "user", t))
            return out
        if isinstance(content, list):
            texts = []
            for b in content:
                if not isinstance(b, dict):
                    continue
                bt = b.get("type")
                if bt == "text":
                    t = _clean_user_text(b.get("text", ""))
                    if t:
                        texts.append(t)
                elif bt == "tool_result" and not role_prefix:  # subagent tool noise is skipped
                    t = " ".join(_text_from_content(b.get("content")).split())
                    if t:
                        if b.get("is_error"):
                            t = "[error] " + t
                        out.append((role_prefix + "result", t[:MAX_TOOL_RESULT]))
            if texts:
                out.insert(0, (role_prefix + "user", "\n".join(texts)))
        return out

    # assistant
    if isinstance(content, str):
        if content.strip():
            out.append((role_prefix + "assistant", content.strip()))
        return out
    if isinstance(content, list):
        texts = []
        for b in content:
            if not isinstance(b, dict):
                continue
            bt = b.get("type")
            if bt == "text":
                t = b.get("text", "").strip()
                if t:
                    texts.append(t)
            elif bt == "tool_use" and not role_prefix:
                name = b.get("name", "?")
                out.append((role_prefix + "tool", f"[tool: {name}] {_input_digest(b.get('input'))}"))
        if texts:
            out.insert(0, (role_prefix + "assistant", "\n".join(texts)))
    return out


_RECORD_READERS = []


def _record_reader(reader):
    """Registers a transcript adapter; a new format only adds one decorated reader."""
    _RECORD_READERS.append(reader)
    return reader


@_record_reader
def _read_claude_record(rec: dict, role_prefix: str) -> ParsedRecord | None:
    if rec.get("type") not in ("user", "assistant"):
        return None
    return ParsedRecord(_claude_turns(rec, role_prefix), session=rec.get("sessionId"))


@_record_reader
def _read_codex_record(rec: dict, role_prefix: str) -> ParsedRecord | None:
    """Normalizes the record shapes found in ~/.codex/sessions."""
    typ = rec.get("type")
    payload = rec.get("payload")
    if not isinstance(payload, dict):
        return None

    if typ == "session_meta":
        cwd = payload.get("cwd")
        project = Path(cwd).name if isinstance(cwd, str) and cwd else None
        session = payload.get("session_id") or payload.get("id")
        return ParsedRecord([], project=project, session=session)

    if typ != "response_item":
        return None
    if payload.get("type") != "message" or payload.get("role") not in ("user", "assistant"):
        return ParsedRecord([])

    role = payload["role"]
    block_type = "input_text" if role == "user" else "output_text"
    texts = [
        block.get("text", "").strip()
        for block in payload.get("content", [])
        if isinstance(block, dict) and block.get("type") == block_type
        and isinstance(block.get("text"), str) and block.get("text", "").strip()
    ]
    if role == "user":
        texts = [text for text in (_clean_user_text(text) for text in texts) if text]
    turns = [(role_prefix + role, "\n".join(texts))] if texts else []
    return ParsedRecord(turns)


def read_record(rec: dict, role_prefix: str = "") -> ParsedRecord:
    """Recognizes a transcript format and returns its normalized record."""
    for reader in _RECORD_READERS:
        parsed = reader(rec, role_prefix)
        if parsed is not None:
            return parsed
    return ParsedRecord([])


def turns_from_record(rec: dict, role_prefix: str = "") -> list[tuple[str, str]]:
    """Compatibility interface: normalized (role, text) turns from one JSONL row."""
    return read_record(rec, role_prefix).turns


def chunk(text: str) -> list[str]:
    if len(text) <= CHUNK_SIZE:
        return [text]
    parts = []
    i = 0
    while i < len(text):
        parts.append(text[i : i + CHUNK_SIZE])
        if i + CHUNK_SIZE >= len(text):
            break
        i += STEP
    return parts


# ---------------------------------------------------------------- grouping of turns

def _too_long(t: Turn) -> bool:
    return len(t.text) > CHUNK_SIZE


def group(turns: list[Turn]) -> list[list[Turn]]:
    """Glues consecutive turns into groups that fit a single chunk.

    A lone "yes, do it" has an empty vector — the question it answers sits in another row.
    That is why short turns go into the database together with their neighbours. A turn longer
    than a chunk forms its own group (and is cut as before).
    """
    groups: list[list[Turn]] = []
    current: list[Turn] = []
    length = 0
    for t in turns:
        if _too_long(t):
            if current:
                groups.append(current)
                current, length = [], 0
            groups.append([t])
            continue
        cost = len(t.role) + 2 + len(t.text)  # "role: text"
        total = length + len(TURN_SEPARATOR) + cost if current else cost
        if current and total > CHUNK_SIZE:
            groups.append(current)
            current, length, total = [], 0, cost
        current.append(t)
        length = total
    if current:
        groups.append(current)
    return groups


def _chunks_from_group(group_: list[Turn], role_prefix: str) -> list[Chunk]:
    """Group -> chunks ready to store. Glued turns get their role as a prefix in the text."""
    roles = {t.role for t in group_}
    role = roles.pop() if len(roles) == 1 else role_prefix + MIXED_ROLE
    if len(group_) == 1:
        text = group_[0].text  # a single turn stays exactly as it was
    else:
        text = TURN_SEPARATOR.join(f"{t.role}: {t.text}" for t in group_)
    first = group_[0]
    return [Chunk(first.line, i, first.ts, role, c) for i, c in enumerate(chunk(text))]


def _tail_open(group_: list[Turn], mtime: float) -> bool:
    """Can the last group still grow by a turn nobody has appended yet?"""
    if len(group_) == 1 and _too_long(group_[0]):
        return False  # a long turn is not glued to its neighbours anyway
    return time.time() - mtime <= TAIL_CLOSING_AGE_S


# ---------------------------------------------------------------- files

def _home_files() -> list[Path]:
    """Orca session transcripts: ~/<uuid>.jsonl and the contents of ~/<uuid>/ (without walking all of $HOME)."""
    if not HOME_DIR.is_dir():
        return []
    files: list[Path] = []
    try:
        entries = list(HOME_DIR.iterdir())
    except OSError:
        return []
    for e in entries:
        try:
            if e.is_file():
                if e.suffix == ".jsonl":
                    files.append(e)
            elif e.is_dir() and _UUID.fullmatch(e.name):
                files.extend(q for q in e.rglob("*.jsonl") if q.is_file())
        except OSError:  # e.g. a directory we cannot read
            continue
    return files


def find_files() -> list[Path]:
    files: list[Path] = []
    if PROJECTS_DIR.is_dir():
        files.extend(p for p in PROJECTS_DIR.rglob("*.jsonl") if p.is_file())
    if CODEX_SESSIONS_DIR.is_dir():
        files.extend(p for p in CODEX_SESSIONS_DIR.rglob("*.jsonl") if p.is_file())
    files.extend(_home_files())
    return sorted(files)


def describe_file(p: Path) -> tuple[str, str, str]:
    """(project, session, role prefix) based on where the file lies."""
    try:
        p.relative_to(CODEX_SESSIONS_DIR)
        return "codex", p.stem, ""
    except ValueError:
        pass
    try:
        rel = p.relative_to(PROJECTS_DIR).parts
    except ValueError:
        # Orca: ~/<uuid>.jsonl or ~/<uuid>/subagents/.../agent-xxx.jsonl
        rel = p.relative_to(HOME_DIR).parts
        if len(rel) == 1:
            return HOME_PROJECT, p.stem, ""
        return HOME_PROJECT, rel[0], "agent:"
    project = rel[0] if len(rel) > 1 else "?"
    if len(rel) == 2:
        return project, p.stem, ""
    # <project>/<session>/subagents/.../agent-xxx.jsonl
    return project, rel[1], "agent:"


def _label(p: Path) -> str:
    """Short path for the log — files outside the projects directory show as a bare name."""
    try:
        return str(p.relative_to(PROJECTS_DIR))
    except ValueError:
        return p.name


def _read_new_lines(p: Path, offset: int) -> tuple[list[tuple[int, str]], int]:
    """Returns [(start_byte, line)] from the offset and the new offset (complete lines only)."""
    lines = []
    with open(p, "rb") as f:
        f.seek(offset)
        pos = offset
        while True:
            raw = f.readline()
            if not raw:
                break
            if not raw.endswith(b"\n"):
                break  # unfinished line — somebody is still writing
            lines.append((pos, raw.decode("utf-8", errors="replace")))
            pos += len(raw)
    return lines, pos


def _turns_from_lines(lines: list[tuple[int, str]], start_line: int, role_prefix: str,
                      default_ts: str) -> tuple[list[Turn], str, str | None, str | None]:
    """Parses lines -> turns plus session/project metadata found in the records."""
    turns: list[Turn] = []
    ts = default_ts
    session_from_record = None
    project_from_record = None
    nr = start_line
    for _, l in lines:
        nr += 1
        l = l.strip()
        if not l or not l.startswith("{"):
            continue
        try:
            rec = json.loads(l)
        except json.JSONDecodeError:
            continue
        if not isinstance(rec, dict):
            continue
        ts = rec.get("timestamp") or ts
        parsed = read_record(rec, role_prefix)
        if session_from_record is None and parsed.session:
            session_from_record = parsed.session
        if project_from_record is None and parsed.project:
            project_from_record = parsed.project
        for role, text in parsed.turns:
            # lone UTF-16 surrogates (broken emoji in JSON) blow up the tokenizer and SQLite
            text = mask(text).encode("utf-8", errors="replace").decode("utf-8").strip()
            if len(text) < MIN_LENGTH:
                continue
            turns.append(Turn(nr, ts, role, text))
    return turns, ts, session_from_record, project_from_record


def _group_boundary(group_: list[Turn], lines: list[tuple[int, str]], start_line: int, end_offset: int) -> tuple[int, int]:
    """(offset, line number) right after the last line of the group — where to resume once it is closed."""
    last = max(t.line for t in group_)
    nxt = last - start_line  # index of the next line in `lines`
    return (lines[nxt][0] if nxt < len(lines) else end_offset), last


# ---------------------------------------------------------------- OpenCode (SQLite, read only)
#
# One session of the OpenCode database is one "file" of Lore: its key is `<db>#<session id>`, a
# "line" is the ordinal of a message in the session (1, 2, ...), and the files row keeps
# mtime = the newest change in the session (s), size = its message count, offset = line = the
# messages already stored. The schema was read on OpenCode 1.18.33 only, so it is checked before
# every read: a missing table or column is an OpencodeError (said and recorded in meta), never a
# crash and never silence. No OpenCode on the machine (no database) is the normal case: skipped.

OPENCODE_COLUMNS = {
    "session": ("id", "directory", "parent_id", "time_updated"),
    "message": ("id", "session_id", "time_created", "time_updated", "data"),
    "part": ("id", "message_id", "session_id", "time_updated", "data"),
}


class OpencodeError(Exception):
    """The OpenCode database exists but cannot be read the way this code expects."""


@dataclass
class OpencodeSession:
    id: str
    key: str  # the `file` of its chunks
    project: str
    session: str  # the root session — a subagent's conversation is filed under its parent's
    role_prefix: str
    count: int  # messages
    stamp: float  # the newest change in the session, seconds


def opencode_db() -> Path:
    return OPENCODE_DB or HOME_DIR / ".local" / "share" / "opencode" / "opencode.db"


def opencode_connect(path: Path | None = None) -> sqlite3.Connection | None:
    """A read-only connection to the OpenCode database, its schema checked; None = no OpenCode here.

    mode=ro: nothing is ever written to it, and a WAL reader does not block a running OpenCode.
    """
    path = path or opencode_db()
    if not path.is_file():
        return None
    try:
        oc = sqlite3.connect(f"{path.as_uri()}?mode=ro", uri=True, timeout=5)
    except sqlite3.Error as e:
        raise OpencodeError(f"cannot open {path}: {e}") from e
    try:
        oc.execute("PRAGMA query_only=ON")
        for table, needed in OPENCODE_COLUMNS.items():
            have = {r[1] for r in oc.execute(f"PRAGMA table_info({table})")}
            if not have:
                raise OpencodeError(f"{path}: no table {table!r} - an OpenCode version this code does not know")
            missing = [c for c in needed if c not in have]
            if missing:
                raise OpencodeError(f"{path}: table {table!r} lacks {', '.join(missing)}"
                                    " - an OpenCode version this code does not know")
    except sqlite3.Error as e:
        oc.close()
        raise OpencodeError(f"cannot read {path}: {e}") from e
    except OpencodeError:
        oc.close()
        raise
    return oc


def opencode_ts(ms) -> str:
    return datetime.fromtimestamp(ms / 1000, tz=timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")


def _json(raw) -> dict | None:
    try:
        data = json.loads(raw)
    except (TypeError, ValueError):
        return None
    return data if isinstance(data, dict) else None


def opencode_sessions(oc: sqlite3.Connection, path: Path | None = None) -> list[OpencodeSession]:
    path = path or opencode_db()
    rows = oc.execute(
        "SELECT s.id, s.directory, s.parent_id, s.time_updated,"
        " (SELECT count(*) FROM message m WHERE m.session_id = s.id),"
        " (SELECT max(m.time_updated) FROM message m WHERE m.session_id = s.id),"
        " (SELECT max(p.time_updated) FROM part p WHERE p.session_id = s.id)"
        " FROM session s ORDER BY s.time_created, s.id"
    ).fetchall()
    parent = {r[0]: r[2] for r in rows}
    out = []
    for sid, directory, parent_id, updated, count, msg_updated, part_updated in rows:
        root, seen = sid, {sid}
        while parent.get(root) and parent[root] not in seen:  # a cycle must not hang the indexer
            root = parent[root]
            seen.add(root)
        project = Path(directory).name if isinstance(directory, str) and directory.strip("/\\") else ""
        stamp = max(v for v in (updated, msg_updated, part_updated, 0) if isinstance(v, (int, float))) / 1000
        out.append(OpencodeSession(sid, f"{path}#{sid}", project or OPENCODE_PROJECT, root,
                                   "agent:" if parent_id else "", count or 0, float(stamp)))
    return out


def _opencode_texts(oc: sqlite3.Connection, session_id: str, message_ids: set[str]) -> tuple[dict[str, list[str]], int]:
    """{message id: its text parts in order} and the number of parts whose JSON is unreadable."""
    texts: dict[str, list[str]] = {}
    bad = 0
    for mid, raw in oc.execute("SELECT message_id, data FROM part WHERE session_id=? ORDER BY id", (session_id,)):
        if mid not in message_ids:
            continue
        data = _json(raw)
        if data is None:
            bad += 1
            continue
        if data.get("type") != "text" or data.get("synthetic") or data.get("ignored"):
            continue
        if isinstance(data.get("text"), str):
            texts.setdefault(mid, []).append(data["text"])
    return texts, bad


def _opencode_rewritten(oc: sqlite3.Connection, s: OpencodeSession, offset: int, since: float) -> bool:
    """Did a stored message change after the last pass (an undo, an edit)? Then the session goes again from zero."""
    if offset <= 0:
        return False
    head = oc.execute("SELECT id, time_created FROM message WHERE session_id=? ORDER BY time_created, id LIMIT ?",
                      (s.id, offset)).fetchall()
    since_ms = since * 1000
    if any(created > since_ms for _, created in head):
        return True  # a message inserted among the stored ones: the ordinals moved
    ids = {mid for mid, _ in head}
    for mid, raw in oc.execute("SELECT message_id, data FROM part WHERE session_id=? AND time_updated>?",
                               (s.id, since_ms)):
        data = _json(raw)
        if mid in ids and data is not None and data.get("type") == "text":
            return True
    return False


def _opencode_turns(oc: sqlite3.Connection, s: OpencodeSession, offset: int) -> tuple[list[Turn], int, int]:
    """Turns of the messages after `offset`, the number of messages read, unreadable rows.

    Reading stops before an assistant message still being written (no time.completed) in a session
    touched within TAIL_CLOSING_AGE_S - its text is not final yet; older ones count as finished."""
    rows = oc.execute("SELECT id, time_created, data FROM message WHERE session_id=? ORDER BY time_created, id"
                      " LIMIT -1 OFFSET ?", (s.id, offset)).fetchall()
    texts, bad = _opencode_texts(oc, s.id, {r[0] for r in rows})
    recent = time.time() - s.stamp <= TAIL_CLOSING_AGE_S
    turns: list[Turn] = []
    read = 0
    for nr, (mid, created, raw) in enumerate(rows, start=offset + 1):
        data = _json(raw)
        if data is None:
            bad += 1
            read += 1
            continue
        role = data.get("role")
        if role == "assistant" and recent and not (data.get("time") or {}).get("completed"):
            break
        read += 1
        if role not in ("user", "assistant"):
            continue
        parts = texts.get(mid, [])
        if role == "user":
            parts = [_clean_user_text(t) for t in parts]
        text = "\n".join(t.strip() for t in parts if t and t.strip())
        text = mask(text).encode("utf-8", errors="replace").decode("utf-8").strip()
        if len(text) < MIN_LENGTH:
            continue
        ms = (data.get("time") or {}).get("created")
        turns.append(Turn(nr, opencode_ts(ms if isinstance(ms, (int, float)) else created), s.role_prefix + role, text))
    return turns, read, bad


def opencode_agent_parts(oc: sqlite3.Connection, after_ms: int) -> Iterator[tuple[int, str, dict]]:
    """(time_updated ms, root session, part) of every assistant part changed after `after_ms`, oldest
    first — for lore.usage, which looks for the agent's text and tool input. A row with unreadable
    JSON is skipped here; the indexer's pass over the same database counts and reports it."""
    sessions = {s.id: s.session for s in opencode_sessions(oc)}
    roles = {}
    for mid, raw in oc.execute("SELECT id, data FROM message"):
        data = _json(raw)
        roles[mid] = data.get("role") if data else None
    for updated, mid, sid, raw in oc.execute(
            "SELECT time_updated, message_id, session_id, data FROM part WHERE time_updated>? ORDER BY time_updated, id",
            (after_ms,)):
        if roles.get(mid) != "assistant":
            continue
        data = _json(raw)
        if data is not None:
            yield updated, sessions.get(sid, sid), data


# ---------------------------------------------------------------- cross-process lock

def _acquire_lock(path: Path | None = None) -> bool:
    path = path or LOCK_PATH
    for _ in range(2):
        try:
            fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            os.write(fd, str(os.getpid()).encode())
            os.close(fd)
            return True
        except FileExistsError:
            try:
                age = time.time() - path.stat().st_mtime
            except FileNotFoundError:
                continue
            if age > LOCK_STALE_S:
                log(f"removing a stale lock {path.name} ({age:.0f}s)")
                try:
                    path.unlink()
                except FileNotFoundError:
                    pass
                continue
            return False
    return False


def _refresh_lock(path: Path | None = None) -> None:
    try:
        os.utime(path or LOCK_PATH, None)
    except FileNotFoundError:
        pass


def _release_lock(path: Path | None = None) -> None:
    try:
        (path or LOCK_PATH).unlink()
    except FileNotFoundError:
        pass


# ---------------------------------------------------------------- main loop

def _delete_file_chunks(conn: sqlite3.Connection, path: str, from_line: int | None = None) -> None:
    """Deletes the chunks of a file — all of them or only those above the resume point (guard against duplicates)."""
    if from_line is None:
        where, args = "file=?", (path,)
    else:
        where, args = "file=? AND line>?", (path, from_line)
    ids = [r[0] for r in conn.execute(f"SELECT id FROM chunks WHERE {where}", args)]
    if not ids:
        return
    for i in ids:
        conn.execute("INSERT INTO chunks_fts(chunks_fts, rowid, text) SELECT 'delete', id, text FROM chunks WHERE id=?", (i,))
    conn.execute(f"DELETE FROM vectors WHERE chunk_id IN (SELECT id FROM chunks WHERE {where})", args)
    conn.execute(f"DELETE FROM chunks WHERE {where}", args)


def _tail_to_close(offset: int, st: os.stat_result) -> bool:
    """File unchanged, but an unwritten group hangs on it that nothing will extend any more."""
    return offset < st.st_size and time.time() - st.st_mtime > TAIL_CLOSING_AGE_S


_unknown_warned: set[str | None] = set()


def _embed(chunks: list[Chunk], model: str | None, text_only: bool = False):
    """Vectors for new chunks, or None when the database's model is one this code cannot run.

    None is not silent: the chunk is stored without a vector (full-text search finds it at once),
    it is said out loud, and `python -m lore.migrate` gives every such chunk a vector.
    In the text-only mode None is the plan, not a fault: no model is touched and nothing is said
    per chunk - the mode itself is recorded once per pass (see index()).
    """
    if not chunks or text_only:
        return None
    if model not in MODELS:
        if model not in _unknown_warned:
            _unknown_warned.add(model)
            log(f"WARNING: the database's vectors are of an unknown model {model!r} - new chunks are stored "
                "WITHOUT vectors until `python -m lore.migrate` converts the archive")
        return None
    return embed_passages([c.text for c in chunks], model=model)


def process_file(conn: sqlite3.Connection, p: Path, text_only: bool = False) -> int:
    """Adds the new lines of one file. Returns the number of new chunks (text_only: without vectors)."""
    path = str(p)
    st = p.stat()
    row = conn.execute(
        "SELECT mtime, size, offset, line, project, session FROM files WHERE path=?", (path,)
    ).fetchone()
    if row and row[0] == st.st_mtime and row[1] == st.st_size and not _tail_to_close(row[2], st):
        return 0
    offset, start_line = (row[2], row[3]) if row else (0, 0)
    from_scratch = False
    if st.st_size < offset:
        from_scratch = True  # file truncated/overwritten — we index it from zero
        offset, start_line = 0, 0

    project, session, role_prefix = describe_file(p)
    if row and not from_scratch:
        project = row[4] or project
        session = row[5] or session
    last_ts = ""
    if row and not from_scratch:
        r = conn.execute("SELECT ts FROM chunks WHERE file=? ORDER BY line DESC, part DESC LIMIT 1", (path,)).fetchone()
        last_ts = r[0] if r else ""
    if not last_ts:
        last_ts = datetime.fromtimestamp(st.st_mtime, tz=timezone.utc).isoformat().replace("+00:00", "Z")

    lines, end_offset = _read_new_lines(p, offset)
    turns, _, session_rec, project_rec = _turns_from_lines(lines, start_line, role_prefix, last_ts)
    if not role_prefix and session_rec:
        session = session_rec
    if not role_prefix and project_rec:
        project = project_rec

    groups = group(turns)
    if groups and _tail_open(groups[-1], st.st_mtime):
        groups.pop()  # the last group may still grow — we store it once it closes
    if groups:
        # the offset stops at the end of the last CLOSED group: the rest will be read again
        new_offset, new_line = _group_boundary(groups[-1], lines, start_line, end_offset)
    elif turns:
        new_offset, new_line = offset, start_line
    else:
        new_offset, new_line = end_offset, start_line + len(lines)
    chunks = [c for g in groups for c in _chunks_from_group(g, role_prefix)]

    # embeddings are computed outside the transaction (we do not hold a write lock for minutes),
    # with the model of the vectors ALREADY in the database — during a conversion that is the old
    # one (the conversion picks these chunks up by itself), after it the new one
    model = active_model(conn)
    emb = _embed(chunks, model, text_only)

    # one stamp for the whole pass: this is the moment the material entered the database, and the
    # harvest reads it instead of `ts` (the id breaks the ties inside a pass). See lore/facts.py.
    landed = now_iso()

    conn.execute("BEGIN IMMEDIATE")
    try:
        if active_model(conn) != model:
            # the conversion switched models while we were embedding: these vectors belong to the
            # old one and must not land among the new ones — start over with the model there now
            conn.execute("ROLLBACK")
            log(f"vector model changed to {active_model(conn)} while indexing {_label(p)} - embedding again")
            return process_file(conn, p, text_only)
        # somebody may have got there before us (another window / the scheduler)
        row2 = conn.execute("SELECT mtime, size, offset FROM files WHERE path=?", (path,)).fetchone()
        if row2 and row2[0] == st.st_mtime and row2[1] == st.st_size and row2[2] >= new_offset:
            conn.execute("ROLLBACK")
            return 0
        _store(conn, path, project, session, chunks, emb, landed, None if from_scratch else start_line,
               (st.st_mtime, st.st_size, new_offset, new_line))
        conn.execute("COMMIT")
    except Exception:
        conn.execute("ROLLBACK")
        raise
    return len(chunks)


def _store(conn: sqlite3.Connection, path: str, project: str, session: str, chunks: list[Chunk], emb, landed: str,
           from_line: int | None, state: tuple) -> None:
    """Inside the caller's transaction: replaces the chunks past `from_line` (None = all) and saves
    the resume point `state` = (mtime, size, offset, line)."""
    _delete_file_chunks(conn, path, from_line=from_line)
    for i, c in enumerate(chunks):
        cur = conn.execute(
            "INSERT INTO chunks(project, session, file, line, part, ts, role, text, indexed_at)"
            " VALUES (?,?,?,?,?,?,?,?,?)",
            (project, session, path, c.line, c.part, c.ts, c.role, c.text, landed),
        )
        cid = cur.lastrowid
        conn.execute("INSERT INTO chunks_fts(rowid, text) VALUES (?,?)", (cid, c.text))
        if emb is not None:
            conn.execute("INSERT INTO vectors(chunk_id, emb) VALUES (?,?)", (cid, emb[i].tobytes()))
    conn.execute(
        "INSERT INTO files(path, mtime, size, offset, line, project, session) VALUES (?,?,?,?,?,?,?) "
        "ON CONFLICT(path) DO UPDATE SET mtime=excluded.mtime, size=excluded.size, "
        "offset=excluded.offset, line=excluded.line, project=excluded.project, session=excluded.session",
        (path, *state, project, session),
    )


def process_opencode_session(conn: sqlite3.Connection, oc: sqlite3.Connection, s: OpencodeSession,
                             text_only: bool = False) -> tuple[int, int]:
    """Adds the new messages of one OpenCode session — process_file for the database.
    Returns (new chunks, unreadable rows met)."""
    path = s.key
    row = conn.execute("SELECT mtime, size, offset FROM files WHERE path=?", (path,)).fetchone()
    stale_tail = bool(row) and row[2] < s.count and time.time() - s.stamp > TAIL_CLOSING_AGE_S
    if row and row[0] == s.stamp and row[1] == s.count and not stale_tail:
        return 0, 0
    offset = row[2] if row else 0
    from_scratch = not row
    if row and (s.count < offset or _opencode_rewritten(oc, s, offset, row[0])):
        from_scratch, offset = True, 0  # messages undone or changed: the session is indexed from zero

    turns, read, bad = _opencode_turns(oc, s, offset)
    groups = group(turns)
    if groups and _tail_open(groups[-1], s.stamp):
        groups.pop()  # the last group may still grow — stored once it closes
    if groups:
        new_offset = max(t.line for t in groups[-1])  # a line is a message ordinal: no byte offsets here
    elif turns:
        new_offset = offset
    else:
        new_offset = offset + read
    chunks = [c for g in groups for c in _chunks_from_group(g, s.role_prefix)]

    model = active_model(conn)
    emb = _embed(chunks, model, text_only)
    landed = now_iso()
    conn.execute("BEGIN IMMEDIATE")
    try:
        if active_model(conn) != model:
            conn.execute("ROLLBACK")
            log(f"vector model changed to {active_model(conn)} while indexing OpenCode {s.id} - embedding again")
            return process_opencode_session(conn, oc, s, text_only)
        row2 = conn.execute("SELECT mtime, size, offset FROM files WHERE path=?", (path,)).fetchone()
        if row2 and row2[0] == s.stamp and row2[1] == s.count and row2[2] >= new_offset:
            conn.execute("ROLLBACK")
            return 0, bad
        _store(conn, path, s.project, s.session, chunks, emb, landed, None if from_scratch else offset,
               (s.stamp, s.count, new_offset, new_offset))
        conn.execute("COMMIT")
    except Exception:
        conn.execute("ROLLBACK")
        raise
    return len(chunks), bad


def _record_opencode(conn: sqlite3.Connection, status: str) -> None:
    conn.execute("INSERT INTO meta(key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",
                 (META_OPENCODE, status))


def index_opencode(conn: sqlite3.Connection, text_only: bool = False, quiet: bool = False,
                   path: Path | None = None) -> tuple[int, int, int]:
    """All OpenCode sessions: (new chunks, sessions changed, sessions). Never raises: a fault is logged
    and recorded in meta (META_OPENCODE, "BLAD ..."), a pass that went well records "ok ...", and a
    machine without OpenCode records "absent" — so an old fault does not hang on after an uninstall."""
    path = path or opencode_db()
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")
    new = changed = 0
    sessions: list[OpencodeSession] = []
    faults: list[str] = []
    bad = 0
    try:
        oc = opencode_connect(path)
    except OpencodeError as e:
        log(f"UWAGA: OpenCode conversations are NOT indexed: {e}")
        _record_opencode(conn, f"BLAD {stamp}: {e}")
        return 0, 0, 0
    if oc is None:
        _record_opencode(conn, "absent")
        return 0, 0, 0
    try:
        sessions = opencode_sessions(oc, path)
        for s in sessions:
            try:
                n, b = process_opencode_session(conn, oc, s, text_only)
            except sqlite3.Error as e:  # one session must not hide the others — but it is said
                faults.append(f"{s.id}: {e}")
                log(f"UWAGA: OpenCode session {s.id} skipped: {e}")
                continue
            bad += b
            if n:
                new += n
                changed += 1
                if not quiet:
                    log(f"+{n:5d}  opencode {s.project}/{s.id}")
            _refresh_lock()
    except sqlite3.Error as e:
        faults.append(str(e))
        log(f"UWAGA: OpenCode database {path} could not be read: {e}")
    finally:
        oc.close()
    if bad:
        faults.append(f"{bad} rows with unreadable JSON skipped")
        log(f"UWAGA: OpenCode: {bad} messages/parts with unreadable JSON skipped - a format this code does not know?")
    if faults:
        _record_opencode(conn, f"BLAD {stamp}: " + "; ".join(faults)[:1000])
    else:
        _record_opencode(conn, f"ok {stamp}: {len(sessions)} sessions")
    return new, changed, len(sessions)


def index(conn: sqlite3.Connection | None = None, quiet: bool = False, text_only: bool = False) -> int:
    """A full incremental pass over all files. Returns the number of new chunks.

    text_only: chunks go in without vectors and the model is never loaded (see the module docstring);
    the mode is recorded in meta at the start of the pass, so every reader sees the same state.
    """
    if not _acquire_lock():
        if not quiet:
            log("another process is indexing right now — skipping")
        return 0
    own = conn is None
    if own:
        conn = connect()
    start = time.time()
    new = 0
    changed_files = 0
    try:
        record_index_mode(conn, text_only)
        files = find_files()
        for p in files:
            try:
                n = process_file(conn, p, text_only)
            except sqlite3.OperationalError as e:
                log(f"skipped {p.name}: {e}")
                continue
            except Exception as e:
                log(f"error in {p}: {e!r}")
                continue
            if n:
                new += n
                changed_files += 1
                if not quiet:
                    log(f"+{n:5d}  {_label(p)}")
            _refresh_lock()
        oc_new, oc_changed, oc_sessions = index_opencode(conn, text_only, quiet)
        new += oc_new
        changed_files += oc_changed
        conn.execute(
            "INSERT INTO meta(key, value) VALUES ('last_indexed', ?) "
            "ON CONFLICT(key) DO UPDATE SET value=excluded.value",
            (datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),),
        )
        if not quiet:
            opencode = f" + {oc_sessions} OpenCode sessions" if oc_sessions else ""
            log(f"done: {new} new chunks from {changed_files}/{len(files)} files{opencode} in {time.time() - start:.1f}s")
    finally:
        _release_lock()
        if own:
            conn.close()
    return new


def remask(conn: sqlite3.Connection, text_only: bool = False) -> int:
    """Masks all chunks again (after a pattern change); the changed ones get new embeddings.

    text_only: no model - the old vector of a changed chunk is dropped instead (it still encodes
    the unmasked text); `python -m lore.migrate` gives it a new one once lore is installed.
    """
    changed: list[tuple[int, str]] = []
    for cid, text in conn.execute("SELECT id, text FROM chunks"):
        new = mask(text)
        if new != text:
            changed.append((cid, new))
    if not changed:
        return 0
    model = active_model(conn)
    emb = embed_passages([t for _, t in changed], model=model) if model in MODELS and not text_only else None
    conn.execute("BEGIN IMMEDIATE")
    try:
        if active_model(conn) != model:
            conn.execute("ROLLBACK")
            log("vector model changed during remask - running it again")
            return remask(conn, text_only)
        building = has_table(conn, NEXT_TABLE)
        for i, (cid, new) in enumerate(changed):
            conn.execute("INSERT INTO chunks_fts(chunks_fts, rowid, text) SELECT 'delete', id, text FROM chunks WHERE id=?", (cid,))
            conn.execute("UPDATE chunks SET text=? WHERE id=?", (new, cid))
            conn.execute("INSERT INTO chunks_fts(rowid, text) VALUES (?,?)", (cid, new))
            if emb is not None:
                conn.execute("UPDATE vectors SET emb=? WHERE chunk_id=?", (emb[i].tobytes(), cid))
            elif text_only:
                conn.execute("DELETE FROM vectors WHERE chunk_id=?", (cid,))
            if building:  # a new vector of the old text is wrong; the conversion embeds it again
                conn.execute(f"DELETE FROM {NEXT_TABLE} WHERE chunk_id=?", (cid,))
        conn.execute("COMMIT")
    except Exception:
        conn.execute("ROLLBACK")
        raise
    log(f"remasked {len(changed)} chunks")
    return len(changed)


def main() -> int:
    text_only = "--text-only" in sys.argv
    conn = connect()
    try:
        if "--remask" in sys.argv:
            remask(conn, text_only)
        new = index(conn, text_only=text_only)
        sessions = conn.execute("SELECT count(DISTINCT session) FROM chunks").fetchone()[0]
        total = conn.execute("SELECT count(*) FROM chunks").fetchone()[0]
        mode = "full text only, no vectors" if text_only else "full text + vectors"
        log(f"database: {DB_PATH} | sessions: {sessions} | chunks: {total} | new now: {new} | mode: {mode}")
    finally:
        conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
