"""Incremental indexer of Claude Code transcripts (~/.claude/projects/**/*.jsonl and ~/<uuid>*.jsonl from Orca).

Run: uv --directory C:\\dev\\claude-worker\\lore run python -m lore.index
"""

from __future__ import annotations

import json
import os
import re
import sqlite3
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from .db import DB_PATH, PROJECTS_DIR, connect, embed_passages, log
from .masking import mask

CHUNK_SIZE = 1500
OVERLAP = 200
STEP = CHUNK_SIZE - OVERLAP
MAX_TOOL_INPUT = 200
MAX_TOOL_RESULT = 400
MIN_LENGTH = 3

TURN_SEPARATOR = "\n\n"
MIXED_ROLE = "conversation"
# the last group is not written — the session may still extend it; but we do not wait forever
TAIL_CLOSING_AGE_S = 24 * 60 * 60

LOCK_PATH = DB_PATH.with_suffix(".lock")
LOCK_STALE_S = 15 * 60

# sessions started by Orca drop their transcripts loose in the home directory
HOME_DIR = Path.home()
CODEX_SESSIONS_DIR = HOME_DIR / ".codex" / "sessions"
HOME_PROJECT = "orca"
_UUID = re.compile(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", re.I)

# user rows generated by Claude Code itself, worthless as memory
_NOISE_PREFIXES = (
    "<task-notification>",
    "<local-command",
    "<ide_opened_file>",
    "<ide_selection>",
    "<command-name>",
    "<command-message>",
    "<bash-input>",
    "<bash-stdout>",
    "<bash-stderr>",
    "[Request interrupted",
    "Base directory for this skill",
    "Caveat: The messages below",
)
_SYSTEM_REMINDER = re.compile(r"<system-reminder>.*?</system-reminder>", re.DOTALL)


@dataclass
class Turn:
    """A single turn from a transcript — the input material for grouping."""

    line: int
    ts: str
    role: str
    text: str


@dataclass
class Chunk:
    line: int
    part: int
    ts: str
    role: str
    text: str


@dataclass
class ParsedRecord:
    """One transcript record normalized at the format seam."""

    turns: list[tuple[str, str]]
    project: str | None = None
    session: str | None = None


# ---------------------------------------------------------------- record parsing

def _text_from_content(content) -> str:
    """Joins `text` blocks (or returns the string) — for tool results."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "\n".join(b.get("text", "") for b in content if isinstance(b, dict) and b.get("type") == "text")
    return ""


def _input_digest(inp) -> str:
    if isinstance(inp, dict):
        # the most telling fields first
        for k in ("command", "description", "pattern", "file_path", "query", "prompt", "zapytanie"):
            if k in inp and isinstance(inp[k], str):
                return " ".join(inp[k].split())[:MAX_TOOL_INPUT]
        s = json.dumps(inp, ensure_ascii=False)
    else:
        s = str(inp)
    return " ".join(s.split())[:MAX_TOOL_INPUT]


def _clean_user_text(t: str) -> str:
    t = _SYSTEM_REMINDER.sub("", t).strip()
    if not t or t.startswith(_NOISE_PREFIXES):
        return ""
    return t


def _claude_turns(rec: dict, role_prefix: str = "") -> list[tuple[str, str]]:
    """Returns normalized turns from one Claude Code JSONL row."""
    typ = rec.get("type")
    if typ not in ("user", "assistant"):
        return []
    if rec.get("isMeta") or rec.get("isApiErrorMessage"):
        return []
    msg = rec.get("message") or {}
    content = msg.get("content")
    out: list[tuple[str, str]] = []

    if typ == "user":
        if rec.get("isCompactSummary"):
            t = _text_from_content(content).strip()
            if t:
                out.append((role_prefix + "summary", t))
            return out
        if isinstance(content, str):
            t = _clean_user_text(content)
            if t:
                out.append((role_prefix + "user", t))
            return out
        if isinstance(content, list):
            texts = []
            for b in content:
                if not isinstance(b, dict):
                    continue
                bt = b.get("type")
                if bt == "text":
                    t = _clean_user_text(b.get("text", ""))
                    if t:
                        texts.append(t)
                elif bt == "tool_result" and not role_prefix:  # subagent tool noise is skipped
                    t = " ".join(_text_from_content(b.get("content")).split())
                    if t:
                        if b.get("is_error"):
                            t = "[error] " + t
                        out.append((role_prefix + "result", t[:MAX_TOOL_RESULT]))
            if texts:
                out.insert(0, (role_prefix + "user", "\n".join(texts)))
        return out

    # assistant
    if isinstance(content, str):
        if content.strip():
            out.append((role_prefix + "assistant", content.strip()))
        return out
    if isinstance(content, list):
        texts = []
        for b in content:
            if not isinstance(b, dict):
                continue
            bt = b.get("type")
            if bt == "text":
                t = b.get("text", "").strip()
                if t:
                    texts.append(t)
            elif bt == "tool_use" and not role_prefix:
                name = b.get("name", "?")
                out.append((role_prefix + "tool", f"[tool: {name}] {_input_digest(b.get('input'))}"))
        if texts:
            out.insert(0, (role_prefix + "assistant", "\n".join(texts)))
    return out


_RECORD_READERS = []


def _record_reader(reader):
    """Registers a transcript adapter; a new format only adds one decorated reader."""
    _RECORD_READERS.append(reader)
    return reader


@_record_reader
def _read_claude_record(rec: dict, role_prefix: str) -> ParsedRecord | None:
    if rec.get("type") not in ("user", "assistant"):
        return None
    return ParsedRecord(_claude_turns(rec, role_prefix), session=rec.get("sessionId"))


@_record_reader
def _read_codex_record(rec: dict, role_prefix: str) -> ParsedRecord | None:
    """Normalizes the record shapes found in ~/.codex/sessions."""
    typ = rec.get("type")
    payload = rec.get("payload")
    if not isinstance(payload, dict):
        return None

    if typ == "session_meta":
        cwd = payload.get("cwd")
        project = Path(cwd).name if isinstance(cwd, str) and cwd else None
        session = payload.get("session_id") or payload.get("id")
        return ParsedRecord([], project=project, session=session)

    if typ != "response_item":
        return None
    if payload.get("type") != "message" or payload.get("role") not in ("user", "assistant"):
        return ParsedRecord([])

    role = payload["role"]
    block_type = "input_text" if role == "user" else "output_text"
    texts = [
        block.get("text", "").strip()
        for block in payload.get("content", [])
        if isinstance(block, dict) and block.get("type") == block_type
        and isinstance(block.get("text"), str) and block.get("text", "").strip()
    ]
    if role == "user":
        texts = [text for text in (_clean_user_text(text) for text in texts) if text]
    turns = [(role_prefix + role, "\n".join(texts))] if texts else []
    return ParsedRecord(turns)


def read_record(rec: dict, role_prefix: str = "") -> ParsedRecord:
    """Recognizes a transcript format and returns its normalized record."""
    for reader in _RECORD_READERS:
        parsed = reader(rec, role_prefix)
        if parsed is not None:
            return parsed
    return ParsedRecord([])


def turns_from_record(rec: dict, role_prefix: str = "") -> list[tuple[str, str]]:
    """Compatibility interface: normalized (role, text) turns from one JSONL row."""
    return read_record(rec, role_prefix).turns


def chunk(text: str) -> list[str]:
    if len(text) <= CHUNK_SIZE:
        return [text]
    parts = []
    i = 0
    while i < len(text):
        parts.append(text[i : i + CHUNK_SIZE])
        if i + CHUNK_SIZE >= len(text):
            break
        i += STEP
    return parts


# ---------------------------------------------------------------- grouping of turns

def _too_long(t: Turn) -> bool:
    return len(t.text) > CHUNK_SIZE


def group(turns: list[Turn]) -> list[list[Turn]]:
    """Glues consecutive turns into groups that fit a single chunk.

    A lone "yes, do it" has an empty vector — the question it answers sits in another row.
    That is why short turns go into the database together with their neighbours. A turn longer
    than a chunk forms its own group (and is cut as before).
    """
    groups: list[list[Turn]] = []
    current: list[Turn] = []
    length = 0
    for t in turns:
        if _too_long(t):
            if current:
                groups.append(current)
                current, length = [], 0
            groups.append([t])
            continue
        cost = len(t.role) + 2 + len(t.text)  # "role: text"
        total = length + len(TURN_SEPARATOR) + cost if current else cost
        if current and total > CHUNK_SIZE:
            groups.append(current)
            current, length, total = [], 0, cost
        current.append(t)
        length = total
    if current:
        groups.append(current)
    return groups


def _chunks_from_group(group_: list[Turn], role_prefix: str) -> list[Chunk]:
    """Group -> chunks ready to store. Glued turns get their role as a prefix in the text."""
    roles = {t.role for t in group_}
    role = roles.pop() if len(roles) == 1 else role_prefix + MIXED_ROLE
    if len(group_) == 1:
        text = group_[0].text  # a single turn stays exactly as it was
    else:
        text = TURN_SEPARATOR.join(f"{t.role}: {t.text}" for t in group_)
    first = group_[0]
    return [Chunk(first.line, i, first.ts, role, c) for i, c in enumerate(chunk(text))]


def _tail_open(group_: list[Turn], mtime: float) -> bool:
    """Can the last group still grow by a turn nobody has appended yet?"""
    if len(group_) == 1 and _too_long(group_[0]):
        return False  # a long turn is not glued to its neighbours anyway
    return time.time() - mtime <= TAIL_CLOSING_AGE_S


# ---------------------------------------------------------------- files

def _home_files() -> list[Path]:
    """Orca session transcripts: ~/<uuid>.jsonl and the contents of ~/<uuid>/ (without walking all of $HOME)."""
    if not HOME_DIR.is_dir():
        return []
    files: list[Path] = []
    try:
        entries = list(HOME_DIR.iterdir())
    except OSError:
        return []
    for e in entries:
        try:
            if e.is_file():
                if e.suffix == ".jsonl":
                    files.append(e)
            elif e.is_dir() and _UUID.fullmatch(e.name):
                files.extend(q for q in e.rglob("*.jsonl") if q.is_file())
        except OSError:  # e.g. a directory we cannot read
            continue
    return files


def find_files() -> list[Path]:
    files: list[Path] = []
    if PROJECTS_DIR.is_dir():
        files.extend(p for p in PROJECTS_DIR.rglob("*.jsonl") if p.is_file())
    if CODEX_SESSIONS_DIR.is_dir():
        files.extend(p for p in CODEX_SESSIONS_DIR.rglob("*.jsonl") if p.is_file())
    files.extend(_home_files())
    return sorted(files)


def describe_file(p: Path) -> tuple[str, str, str]:
    """(project, session, role prefix) based on where the file lies."""
    try:
        p.relative_to(CODEX_SESSIONS_DIR)
        return "codex", p.stem, ""
    except ValueError:
        pass
    try:
        rel = p.relative_to(PROJECTS_DIR).parts
    except ValueError:
        # Orca: ~/<uuid>.jsonl or ~/<uuid>/subagents/.../agent-xxx.jsonl
        rel = p.relative_to(HOME_DIR).parts
        if len(rel) == 1:
            return HOME_PROJECT, p.stem, ""
        return HOME_PROJECT, rel[0], "agent:"
    project = rel[0] if len(rel) > 1 else "?"
    if len(rel) == 2:
        return project, p.stem, ""
    # <project>/<session>/subagents/.../agent-xxx.jsonl
    return project, rel[1], "agent:"


def _label(p: Path) -> str:
    """Short path for the log — files outside the projects directory show as a bare name."""
    try:
        return str(p.relative_to(PROJECTS_DIR))
    except ValueError:
        return p.name


def _read_new_lines(p: Path, offset: int) -> tuple[list[tuple[int, str]], int]:
    """Returns [(start_byte, line)] from the offset and the new offset (complete lines only)."""
    lines = []
    with open(p, "rb") as f:
        f.seek(offset)
        pos = offset
        while True:
            raw = f.readline()
            if not raw:
                break
            if not raw.endswith(b"\n"):
                break  # unfinished line — somebody is still writing
            lines.append((pos, raw.decode("utf-8", errors="replace")))
            pos += len(raw)
    return lines, pos


def _turns_from_lines(lines: list[tuple[int, str]], start_line: int, role_prefix: str,
                      default_ts: str) -> tuple[list[Turn], str, str | None, str | None]:
    """Parses lines -> turns plus session/project metadata found in the records."""
    turns: list[Turn] = []
    ts = default_ts
    session_from_record = None
    project_from_record = None
    nr = start_line
    for _, l in lines:
        nr += 1
        l = l.strip()
        if not l or not l.startswith("{"):
            continue
        try:
            rec = json.loads(l)
        except json.JSONDecodeError:
            continue
        if not isinstance(rec, dict):
            continue
        ts = rec.get("timestamp") or ts
        parsed = read_record(rec, role_prefix)
        if session_from_record is None and parsed.session:
            session_from_record = parsed.session
        if project_from_record is None and parsed.project:
            project_from_record = parsed.project
        for role, text in parsed.turns:
            # lone UTF-16 surrogates (broken emoji in JSON) blow up the tokenizer and SQLite
            text = mask(text).encode("utf-8", errors="replace").decode("utf-8").strip()
            if len(text) < MIN_LENGTH:
                continue
            turns.append(Turn(nr, ts, role, text))
    return turns, ts, session_from_record, project_from_record


def _group_boundary(group_: list[Turn], lines: list[tuple[int, str]], start_line: int, end_offset: int) -> tuple[int, int]:
    """(offset, line number) right after the last line of the group — where to resume once it is closed."""
    last = max(t.line for t in group_)
    nxt = last - start_line  # index of the next line in `lines`
    return (lines[nxt][0] if nxt < len(lines) else end_offset), last


# ---------------------------------------------------------------- cross-process lock

def _acquire_lock() -> bool:
    for _ in range(2):
        try:
            fd = os.open(LOCK_PATH, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            os.write(fd, str(os.getpid()).encode())
            os.close(fd)
            return True
        except FileExistsError:
            try:
                age = time.time() - LOCK_PATH.stat().st_mtime
            except FileNotFoundError:
                continue
            if age > LOCK_STALE_S:
                log(f"removing a stale lock ({age:.0f}s)")
                try:
                    LOCK_PATH.unlink()
                except FileNotFoundError:
                    pass
                continue
            return False
    return False


def _refresh_lock() -> None:
    try:
        os.utime(LOCK_PATH, None)
    except FileNotFoundError:
        pass


def _release_lock() -> None:
    try:
        LOCK_PATH.unlink()
    except FileNotFoundError:
        pass


# ---------------------------------------------------------------- main loop

def _delete_file_chunks(conn: sqlite3.Connection, path: str, from_line: int | None = None) -> None:
    """Deletes the chunks of a file — all of them or only those above the resume point (guard against duplicates)."""
    if from_line is None:
        where, args = "file=?", (path,)
    else:
        where, args = "file=? AND line>?", (path, from_line)
    ids = [r[0] for r in conn.execute(f"SELECT id FROM chunks WHERE {where}", args)]
    if not ids:
        return
    for i in ids:
        conn.execute("INSERT INTO chunks_fts(chunks_fts, rowid, text) SELECT 'delete', id, text FROM chunks WHERE id=?", (i,))
    conn.execute(f"DELETE FROM vectors WHERE chunk_id IN (SELECT id FROM chunks WHERE {where})", args)
    conn.execute(f"DELETE FROM chunks WHERE {where}", args)


def _tail_to_close(offset: int, st: os.stat_result) -> bool:
    """File unchanged, but an unwritten group hangs on it that nothing will extend any more."""
    return offset < st.st_size and time.time() - st.st_mtime > TAIL_CLOSING_AGE_S


def process_file(conn: sqlite3.Connection, p: Path) -> int:
    """Adds the new lines of one file. Returns the number of new chunks."""
    path = str(p)
    st = p.stat()
    row = conn.execute(
        "SELECT mtime, size, offset, line, project, session FROM files WHERE path=?", (path,)
    ).fetchone()
    if row and row[0] == st.st_mtime and row[1] == st.st_size and not _tail_to_close(row[2], st):
        return 0
    offset, start_line = (row[2], row[3]) if row else (0, 0)
    from_scratch = False
    if st.st_size < offset:
        from_scratch = True  # file truncated/overwritten — we index it from zero
        offset, start_line = 0, 0

    project, session, role_prefix = describe_file(p)
    if row and not from_scratch:
        project = row[4] or project
        session = row[5] or session
    last_ts = ""
    if row and not from_scratch:
        r = conn.execute("SELECT ts FROM chunks WHERE file=? ORDER BY line DESC, part DESC LIMIT 1", (path,)).fetchone()
        last_ts = r[0] if r else ""
    if not last_ts:
        last_ts = datetime.fromtimestamp(st.st_mtime, tz=timezone.utc).isoformat().replace("+00:00", "Z")

    lines, end_offset = _read_new_lines(p, offset)
    turns, _, session_rec, project_rec = _turns_from_lines(lines, start_line, role_prefix, last_ts)
    if not role_prefix and session_rec:
        session = session_rec
    if not role_prefix and project_rec:
        project = project_rec

    groups = group(turns)
    if groups and _tail_open(groups[-1], st.st_mtime):
        groups.pop()  # the last group may still grow — we store it once it closes
    if groups:
        # the offset stops at the end of the last CLOSED group: the rest will be read again
        new_offset, new_line = _group_boundary(groups[-1], lines, start_line, end_offset)
    elif turns:
        new_offset, new_line = offset, start_line
    else:
        new_offset, new_line = end_offset, start_line + len(lines)
    chunks = [c for g in groups for c in _chunks_from_group(g, role_prefix)]

    # embeddings are computed outside the transaction (we do not hold a write lock for minutes)
    emb = embed_passages([c.text for c in chunks]) if chunks else None

    conn.execute("BEGIN IMMEDIATE")
    try:
        # somebody may have got there before us (another window / the scheduler)
        row2 = conn.execute("SELECT mtime, size, offset FROM files WHERE path=?", (path,)).fetchone()
        if row2 and row2[0] == st.st_mtime and row2[1] == st.st_size and row2[2] >= new_offset:
            conn.execute("ROLLBACK")
            return 0
        if from_scratch:
            _delete_file_chunks(conn, path)
        else:
            _delete_file_chunks(conn, path, from_line=start_line)
        for i, c in enumerate(chunks):
            cur = conn.execute(
                "INSERT INTO chunks(project, session, file, line, part, ts, role, text) VALUES (?,?,?,?,?,?,?,?)",
                (project, session, path, c.line, c.part, c.ts, c.role, c.text),
            )
            cid = cur.lastrowid
            conn.execute("INSERT INTO chunks_fts(rowid, text) VALUES (?,?)", (cid, c.text))
            conn.execute("INSERT INTO vectors(chunk_id, emb) VALUES (?,?)", (cid, emb[i].tobytes()))
        conn.execute(
            "INSERT INTO files(path, mtime, size, offset, line, project, session) VALUES (?,?,?,?,?,?,?) "
            "ON CONFLICT(path) DO UPDATE SET mtime=excluded.mtime, size=excluded.size, "
            "offset=excluded.offset, line=excluded.line, project=excluded.project, session=excluded.session",
            (path, st.st_mtime, st.st_size, new_offset, new_line, project, session),
        )
        conn.execute("COMMIT")
    except Exception:
        conn.execute("ROLLBACK")
        raise
    return len(chunks)


def index(conn: sqlite3.Connection | None = None, quiet: bool = False) -> int:
    """A full incremental pass over all files. Returns the number of new chunks."""
    if not _acquire_lock():
        if not quiet:
            log("another process is indexing right now — skipping")
        return 0
    own = conn is None
    if own:
        conn = connect()
    start = time.time()
    new = 0
    changed_files = 0
    try:
        files = find_files()
        for p in files:
            try:
                n = process_file(conn, p)
            except sqlite3.OperationalError as e:
                log(f"skipped {p.name}: {e}")
                continue
            except Exception as e:
                log(f"error in {p}: {e!r}")
                continue
            if n:
                new += n
                changed_files += 1
                if not quiet:
                    log(f"+{n:5d}  {_label(p)}")
            _refresh_lock()
        conn.execute(
            "INSERT INTO meta(key, value) VALUES ('last_indexed', ?) "
            "ON CONFLICT(key) DO UPDATE SET value=excluded.value",
            (datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),),
        )
        if not quiet:
            log(f"done: {new} new chunks from {changed_files}/{len(files)} files in {time.time() - start:.1f}s")
    finally:
        _release_lock()
        if own:
            conn.close()
    return new


def remask(conn: sqlite3.Connection) -> int:
    """Masks all chunks again (after a pattern change); the changed ones get new embeddings."""
    changed: list[tuple[int, str]] = []
    for cid, text in conn.execute("SELECT id, text FROM chunks"):
        new = mask(text)
        if new != text:
            changed.append((cid, new))
    if not changed:
        return 0
    emb = embed_passages([t for _, t in changed])
    conn.execute("BEGIN IMMEDIATE")
    try:
        for i, (cid, new) in enumerate(changed):
            conn.execute("INSERT INTO chunks_fts(chunks_fts, rowid, text) SELECT 'delete', id, text FROM chunks WHERE id=?", (cid,))
            conn.execute("UPDATE chunks SET text=? WHERE id=?", (new, cid))
            conn.execute("INSERT INTO chunks_fts(rowid, text) VALUES (?,?)", (cid, new))
            conn.execute("UPDATE vectors SET emb=? WHERE chunk_id=?", (emb[i].tobytes(), cid))
        conn.execute("COMMIT")
    except Exception:
        conn.execute("ROLLBACK")
        raise
    log(f"remasked {len(changed)} chunks")
    return len(changed)


def main() -> int:
    conn = connect()
    try:
        if "--remask" in sys.argv:
            remask(conn)
        new = index(conn)
        sessions = conn.execute("SELECT count(DISTINCT session) FROM chunks").fetchone()[0]
        total = conn.execute("SELECT count(*) FROM chunks").fetchone()[0]
        log(f"database: {DB_PATH} | sessions: {sessions} | chunks: {total} | new now: {new}")
    finally:
        conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
